<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="test" runtimeProfile="wb" qualifiedName="javax.baja.test.TestException" name="TestException" packageName="javax.baja.test" public="true" category="exception">
<description>
TestException is thrown when a verify fails.
</description>
<tag name="@author">Brian Frank</tag>
<tag name="@creation">3 Oct 06</tag>
<tag name="@version">$Revision: 1$ $Date: 10/4/06 3:13:44 PM EDT$</tag>
<tag name="@since">Niagara 3.2</tag>
<extends>
<type class="javax.baja.sys.BajaRuntimeException"/>
</extends>
<!-- javax.baja.test.TestException(java.lang.String, java.lang.Throwable) -->
<constructor name="TestException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<parameter name="cause">
<type class="java.lang.Throwable"/>
</parameter>
<description>
Constructor with specified message and nested exception.
</description>
</constructor>

<!-- javax.baja.test.TestException(java.lang.Throwable) -->
<constructor name="TestException" public="true">
<parameter name="cause">
<type class="java.lang.Throwable"/>
</parameter>
<description>
Constructor with specified nested exception.
</description>
</constructor>

<!-- javax.baja.test.TestException(java.lang.String) -->
<constructor name="TestException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<description>
Constructor with specified message.
</description>
</constructor>

<!-- javax.baja.test.TestException() -->
<constructor name="TestException" public="true">
<description>
No argument constructor.
</description>
</constructor>

</class>
</bajadoc>
